import React from "react";
import Head from "next/head";

export const Meta = (): JSX.Element => (
    <Head>
        <title>Rotten Tomatoes Replica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
);